# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set ZSH Theme
ZSH_THEME="sunrise"

# ZSH Plugins (listed in ~/.oh-my-zsh/plugins/*)
plugins=(osx git brew rbenv pyenv)

# Use oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Fix $PATH
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

# Add Postgres.app to $PATH
PATH="/Applications/Postgres.app/Contents/Versions/9.3/bin:$PATH"

# Ruby
eval "$(rbenv init - zsh)"

alias rake='noglob rake'

# Python
eval "$(pyenv init - zsh)"

# Android
export ANDROID_HOME="/usr/local/opt/android-sdk"
